[project]
name = "codecrafters-shell"
version = "0.1.0"
description = "My shell for codecrafters challenge."
requires-python = ">=3.14"
dependencies = []

[project.scripts]
crafty-shell = "app.main:main"